## Assignment_4.11442

Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically,             when increasing is False, the i-th output column is the input vector raised element-wise              to the power of N - i - 1.

In [1]:
import numpy as np

In [2]:
def Func1(array, size, order = False):
    return np.vander(array, size, order)

a = np.array([2,3,4,5,6])
n = 4
print(Func1(a,n))
print("=" * 20)
print(Func1(a,n,True))

[[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
[[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]]


In [3]:
def Func2(array, size, order = False):
    if order:
        return np.column_stack([array**(size-i-1) for i in range(size)])
    else:
        return np.column_stack([array**(i) for i in range(size)])

a = np.array([2,3,4,5,6])
n = 4
print(Func2(a,n))
print("=" * 20)
print(Func2(a,n,True))

[[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]]
[[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
